version: "3.8"
services:
  web-fe:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - frontend-net
      - backend-net
    volumes:
      - counter-vol:/code
  redis: 
    image: "redis:alpine" 
    networks:
     - backend-net

networks: 
  frontend-net:
  backend-net:
    internal: true
    
volumes:
  counter-vol: {}